name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up target Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Ninja
        run: python -m pip --disable-pip-version-check install ninja

      - name: Setup MSVC
        uses: bus1/cabuild/action/msdevshell@e22aba57d6e74891d059d66501b6b5aed8123c4d  # v1
        with:
          architecture: x64

      - name: Install Meson
        run: python -m pip --disable-pip-version-check install meson

      - name: Build
        run: |
          meson setup build
          cd build
          meson compile
