name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up target Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup MSVC
        uses: bus1/cabuild/action/msdevshell@e22aba57d6e74891d059d66501b6b5aed8123c4d  # v1
        with:
          architecture: x64

      - name: Install dependencies
        run: python -m pip --disable-pip-version-check install meson ninja Cython numpy

      - name: Build
        run: |
          meson setup build
          cd build
          meson compile

      - name: Test C version
        run: .\build\c\npycomplex

      - name: Test Cython version
        run: |
          PYTHONPATH=".\build\cython" python -c "import npycomplex; npycomplex.main()"
